---
- name: copying artifact to local machine
  copy:
          src: /home/devops/workspace/e2e_java/applogin/target/{{archive_file}}
          dest: /tmp

- name: copying artifact to tomcat
  copy:
          src: /tmp/{{archive_file}}
          dest: /opt/tomcat/latest/webapps/
          remote_src: yes
  notify: restart tomcat service
