---
- name: copying artifact to local machine
  copy:
          src: /home/devops/workspace/end_to_end/applogin/target/{{war_file}}
          dest: /tmp

- name: copying artifact to tomcat
  copy:
          src: /tmp/{{war_file}}
          dest: /opt/tomcat/latest/webapps/
          remote_src: yes
  notify: restart tomcat service
